//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panda_Kakei.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Panda_Kakei.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add new expense に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddExpenseText {
            get {
                return ResourceManager.GetString("AddExpenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add new income に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddIncomeText {
            get {
                return ResourceManager.GetString("AddIncomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File access permission is needed to create a new file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertNeedFileAccessMessageText {
            get {
                return ResourceManager.GetString("AlertNeedFileAccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File access permission missing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlertNeedFileAccessTitleText {
            get {
                return ResourceManager.GetString("AlertNeedFileAccessTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AmountText {
            get {
                return ResourceManager.GetString("AmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy database to external folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BackupSettingText {
            get {
                return ResourceManager.GetString("BackupSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Net savings: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BalanceLabelText {
            get {
                return ResourceManager.GetString("BalanceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Net savings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BalanceText {
            get {
                return ResourceManager.GetString("BalanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Net savings of this month: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BalanceThisMonthText {
            get {
                return ResourceManager.GetString("BalanceThisMonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CategoryNameText {
            get {
                return ResourceManager.GetString("CategoryNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CategoryText {
            get {
                return ResourceManager.GetString("CategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change colour  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeColourSettingText {
            get {
                return ResourceManager.GetString("ChangeColourSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompletedTitleText {
            get {
                return ResourceManager.GetString("CompletedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmTitleText {
            get {
                return ResourceManager.GetString("ConfirmTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currency: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrencySettingText {
            get {
                return ResourceManager.GetString("CurrencySettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   € に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrencyText {
            get {
                return ResourceManager.GetString("CurrencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database copy failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DatabaseCopyFailedText {
            get {
                return ResourceManager.GetString("DatabaseCopyFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database will be copied to external storage. If a database already exists in the external storage it will be overwritten. Is that ok? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DatabaseExportConfirmText {
            get {
                return ResourceManager.GetString("DatabaseExportConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database was successfully copied to below file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DatabaseExportSuccessText {
            get {
                return ResourceManager.GetString("DatabaseExportSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading data from external database completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DatabaseImportSuccessText {
            get {
                return ResourceManager.GetString("DatabaseImportSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DatabaseResetButtonText {
            get {
                return ResourceManager.GetString("DatabaseResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database reset completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DatabaseResetCompleteText {
            get {
                return ResourceManager.GetString("DatabaseResetCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to reset database. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DatabaseResetFailedText {
            get {
                return ResourceManager.GetString("DatabaseResetFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete all your financial data stored in this app? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DatabaseResetWarningText {
            get {
                return ResourceManager.GetString("DatabaseResetWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not access to external database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogExternalDatabaseAccessErrorText {
            get {
                return ResourceManager.GetString("DialogExternalDatabaseAccessErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All data saved locally in the app will be overwritten. Is that ok? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogReadBackupWarningText {
            get {
                return ResourceManager.GetString("DialogReadBackupWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogRemoveText {
            get {
                return ResourceManager.GetString("DialogRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit expense に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditExpenseText {
            get {
                return ResourceManager.GetString("EditExpenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit income に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditIncomeText {
            get {
                return ResourceManager.GetString("EditIncomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change last day of every month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndDateSettingText {
            get {
                return ResourceManager.GetString("EndDateSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EndPeriodText {
            get {
                return ResourceManager.GetString("EndPeriodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The entered amount is not a valid number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorAmountText {
            get {
                return ResourceManager.GetString("ErrorAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelCurrencyColumnText {
            get {
                return ResourceManager.GetString("ExcelCurrencyColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel file path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelFilePathLabelText {
            get {
                return ResourceManager.GetString("ExcelFilePathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel file could not be created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelPrintErrorMessage {
            get {
                return ResourceManager.GetString("ExcelPrintErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelPrintErrorTitle {
            get {
                return ResourceManager.GetString("ExcelPrintErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel report was successfully generated on below path: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelReportCompleteText {
            get {
                return ResourceManager.GetString("ExcelReportCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Report Generated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelReportCompleteTitle {
            get {
                return ResourceManager.GetString("ExcelReportCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate Excel report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelReportText {
            get {
                return ResourceManager.GetString("ExcelReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Totalization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelTotalizationString {
            get {
                return ResourceManager.GetString("ExcelTotalizationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expense by category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpenseByCategoryText {
            get {
                return ResourceManager.GetString("ExpenseByCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expense: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpenseLabelText {
            get {
                return ResourceManager.GetString("ExpenseLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expense に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpenseText {
            get {
                return ResourceManager.GetString("ExpenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expense of this month: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpenseThisMonthText {
            get {
                return ResourceManager.GetString("ExpenseThisMonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset external database path to default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtDbPathDefaultButtonText {
            get {
                return ResourceManager.GetString("ExtDbPathDefaultButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The external database path is edited. The edited information will be lost, is that ok? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtDbPathDefaultWarningText {
            get {
                return ResourceManager.GetString("ExtDbPathDefaultWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path to external database: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtDbPathText {
            get {
                return ResourceManager.GetString("ExtDbPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedTitleText {
            get {
                return ResourceManager.GetString("FailedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File access error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileAccessTitleText {
            get {
                return ResourceManager.GetString("FileAccessTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Household account book に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HouseholdAccountText {
            get {
                return ResourceManager.GetString("HouseholdAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Income by category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IncomeByCategoryText {
            get {
                return ResourceManager.GetString("IncomeByCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Income: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IncomeLabelText {
            get {
                return ResourceManager.GetString("IncomeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Income に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IncomeText {
            get {
                return ResourceManager.GetString("IncomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Income of this month: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IncomeThisMonthText {
            get {
                return ResourceManager.GetString("IncomeThisMonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputErrorText {
            get {
                return ResourceManager.GetString("InputErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panda Household Account Book に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPageTitleText {
            get {
                return ResourceManager.GetString("MainPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MemoText {
            get {
                return ResourceManager.GetString("MemoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MonthText {
            get {
                return ResourceManager.GetString("MonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewCategoryText {
            get {
                return ResourceManager.GetString("NewCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pay and remove ads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PaySettingText {
            get {
                return ResourceManager.GetString("PaySettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a photo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PhotoText {
            get {
                return ResourceManager.GetString("PhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreviousText {
            get {
                return ResourceManager.GetString("PreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load data from external database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadBackupSettingText {
            get {
                return ResourceManager.GetString("ReadBackupSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportText {
            get {
                return ResourceManager.GetString("ReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share the app and remove ads に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShareFbSettingText {
            get {
                return ResourceManager.GetString("ShareFbSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortText {
            get {
                return ResourceManager.GetString("SortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartPeriodText {
            get {
                return ResourceManager.GetString("StartPeriodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TotalText {
            get {
                return ResourceManager.GetString("TotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewDataText {
            get {
                return ResourceManager.GetString("ViewDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YearText {
            get {
                return ResourceManager.GetString("YearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
